Screen reader and keyboard accessibility (Potential PR to original repo)
eXplorance/bootstrap-datetimepicker pull request #2
Opened 2016-11-17 14:39 UTC by hanstdam

As you can see, this PR contains a few commits, which is not mine. That's because I based my branch on [Eonasdan/bootstrap-datetimepicker development branch](https://github.com/Eonasdan/bootstrap-datetimepicker/tree/development). The [guidelines for contributing](https://github.com/eXplorance/bootstrap-datetimepicker/blob/explorance-master/CONTRIBUTING.md) states that all PR's should be base in that branch, and since I want to create a PR for the main repo, I've included those commits here.

[Here's a link where you can see my changes in isolation.](https://github.com/eXplorance/bootstrap-datetimepicker/compare/cf911182783f9186366aacaaf03ccc98a2881166...126ada22a8412c02aafa0ce44a6c701b0c4e86a3)

This PR includes a lot of changes, including 1 (arguably 2) breaking change(s). The `options.keyBinds`, has been been renamed to `options.keyBindings` and expanded with context dependent keyboard navigation functions. I renamed the option to make it clear that a change has been introduced.

Other than that, this PR shifts the focus from always being in the input field, to go into the date picker itself. That's in order for the screen reader to read out relevant info based on the users focus. Further several recommendations from [https://www.w3.org/TR/wai-aria-practices/#datepicker](https://www.w3.org/TR/wai-aria-practices/#datepicker) has been implemented.

Check out a demo of the new features here:
https://datetimepicker-demo.neocities.org/

Let me know what you think.

2016-11-17 15:47 UTC, pmairoldi requested changes
Aside from the keybind name change everything looks good. Maybe some tests could be added for these new things since there are a lot of changes.

2016-11-17 15:47 UTC, petester42 commented on src/js/bootstrap-datetimepicker.js
> +                36: 'home',
What does end and home do?

2016-11-17 15:47 UTC, petester42 commented on src/js/bootstrap-datetimepicker.js
> +                });
Is this to toggle between the date and time sections?

2016-11-17 15:47 UTC, petester42 commented on src/js/bootstrap-datetimepicker.js
> +        picker.keyBindings = function (keyBinds) {
I dont think it is a good idea to rename key binds to keyBindings just because it is a breaking change.

2016-11-17 16:36 UTC, hanstdam commented on src/js/bootstrap-datetimepicker.js
> +                36: 'home',
https://www.w3.org/TR/wai-aria-practices/#datepicker suggests that the `end` button _Moves to the last day of the current month._ and `home` button _Moves to the first day of the current month._.
I didn't add those as defaults, as they did not exist before.

2016-11-17 16:43 UTC, hanstdam commented on src/js/bootstrap-datetimepicker.js
> +                });
Yes, among others. (I'm assuming you are talking about the events on `[tabindex="0"]` elements in general, and not the removing of events in the `hide` function, right?). If you have toolbars enabled (if `sideBySide: false`, `showTodayButton: true`, `showClear: true` or `showClose: true`), you can `tab` to the different buttons as well, giving you different context, which the screen reader will tell you about.

2016-11-17 16:44 UTC, hanstdam commented on src/js/bootstrap-datetimepicker.js
> +        picker.keyBindings = function (keyBinds) {
I can change it back, for sure. No biggie.

2016-11-17 16:52 UTC, hanstdam commented
Sure, I'll add some tests.

2016-11-17 20:53 UTC, petester42 commented on src/js/bootstrap-datetimepicker.js
> +                });
ah ok.

2016-11-17 20:54 UTC, petester42 commented on src/js/bootstrap-datetimepicker.js
> +                36: 'home',
If it is best practice for accessibility then why not include the functions?

2016-11-17 21:08 UTC, hanstdam commented on src/js/bootstrap-datetimepicker.js
> +                36: 'home',
You're right. I'll include them.

2016-11-21 17:37 UTC, hanstdam commented on src/js/bootstrap-datetimepicker.js
> +                36: 'home',
Now included

2016-11-21 18:27 UTC, hanstdam commented
Tests add and all changes implemented based on review.

2016-11-21 22:58 UTC, pmairoldi approved these changes

2016-11-21 23:00 UTC, merged